version: "2"
services:
  mysqldb:
    #add the name of image
    image: mysql
    ports:
      - 3309:3306    
    environment:
      MYSQL_DATABASE: club
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - vaidehi-sportsclub-network

  front-end:
    image: vaidehi-sportsclub-frontend
    ports:
      - 8082:80

    networks:
      - vaidehi-sportsclub-network
     

  back-end:
    image: docker-vaidehi/sportsclub-image:latest
    build: . 
    ports: 
      - 8092:8080
    depends_on:
      - mysqldb
   # restart: always
    networks:
      - vaidehi-sportsclub-network
    

networks:
  vaidehi-sportsclub-network:
    driver: bridge
    
volumes:
  db:
   
